# -*- coding: utf-8 -*-
"""Sentiment Analysis_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpC73hQV2tQJa5Z_RE3K31sOis04JVxC
"""

import streamlit as st
import pandas as pd
from textblob import TextBlob
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from transformers import pipeline

# --------------------
# App Title
# --------------------
st.set_page_config(page_title="Sentiment Analysis Dashboard", layout="wide")
st.title("📊 Sentiment Analysis Dashboard")
st.write("Upload customer reviews and get insights about sentiment distribution.")

# --------------------
# Model Selection
# --------------------
model_choice = st.sidebar.selectbox(
    "Choose Sentiment Model:",
    ["TextBlob (Simple)", "HuggingFace BERT (Advanced)"]
)

# HuggingFace model (only load if selected)
if model_choice == "HuggingFace BERT (Advanced)":
    sentiment_pipeline = pipeline("sentiment-analysis")

# --------------------
# Data Input Options
# --------------------
st.sidebar.header("Data Input")
input_option = st.sidebar.radio(
    "Select input type:",
    ["Upload CSV File", "Enter Text Manually"]
)

if input_option == "Upload CSV File":
    uploaded_file = st.file_uploader("Upload a CSV file (must have a column named 'review')", type=["csv"])
    if uploaded_file is not None:
        df = pd.read_csv(uploaded_file)
elif input_option == "Enter Text Manually":
    text_data = st.text_area("Enter customer reviews (one per line):")
    if text_data:
        df = pd.DataFrame({"review": text_data.split("\n")})
else:
    df = None

# --------------------
# Sentiment Analysis Function
# --------------------
def analyze_sentiment(text):
    if model_choice == "TextBlob (Simple)":
        polarity = TextBlob(str(text)).sentiment.polarity
        if polarity > 0:
            return "Positive 😀"
        elif polarity < 0:
            return "Negative 😡"
        else:
            return "Neutral 😐"
    else:
        result = sentiment_pipeline(str(text))[0]["label"]
        if "POS" in result:
            return "Positive 😀"
        elif "NEG" in result:
            return "Negative 😡"
        else:
            return "Neutral 😐"

# --------------------
# Run Analysis
# --------------------
if 'df' in locals() and df is not None and "review" in df.columns:
    st.subheader("📋 Data Preview")
    st.dataframe(df.head())

    df["Sentiment"] = df["review"].apply(analyze_sentiment)

    # Show sentiment distribution
    st.subheader("📈 Sentiment Statistics")
    sentiment_counts = df["Sentiment"].value_counts()

    col1, col2 = st.columns(2)
    with col1:
        st.bar_chart(sentiment_counts)

    with col2:
        fig, ax = plt.subplots()
        ax.pie(sentiment_counts, labels=sentiment_counts.index, autopct='%1.1f%%', startangle=90)
        ax.axis("equal")
        st.pyplot(fig)

    # Average positivity
    avg_positive = round((sentiment_counts.get("Positive 😀", 0) / len(df)) * 100, 2)
    st.success(f"✅ Percentage of happy customers: {avg_positive}%")

    # Top positive & negative reviews
    st.subheader("✨ Highlighted Reviews")
    pos_reviews = df[df["Sentiment"] == "Positive 😀"]["review"].head(3).tolist()
    neg_reviews = df[df["Sentiment"] == "Negative 😡"]["review"].head(3).tolist()

    st.write("**Top Positive Reviews:**")
    for r in pos_reviews:
        st.write(f"✅ {r}")

    st.write("**Top Negative Reviews:**")
    for r in neg_reviews:
        st.write(f"❌ {r}")

    # Wordcloud
    st.subheader("☁️ WordCloud of Reviews")
    text_all = " ".join(df["review"].astype(str))
    wordcloud = WordCloud(width=800, height=400, background_color="white").generate(text_all)
    fig_wc, ax_wc = plt.subplots(figsize=(10, 5))
    ax_wc.imshow(wordcloud, interpolation="bilinear")
    ax_wc.axis("off")
    st.pyplot(fig_wc)

else:
    st.info("👈 Please upload a CSV file or enter text manually to start analysis.")